[[apps]]
title = 'Gamepad UI'
icon_png_path = "https://raw.githubusercontent.com/HashimHS/gow/refs/heads/gamepadui/apps/gamepad-ui/assets/icon.png"

[apps.runner]
type = 'docker'
name = 'WolfGamepad-UI'
image = 'localhost/gamepadui:edge'
env = ['GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*']
devices = []
mounts = []
ports = []
base_create_json = '''{
  "HostConfig": {
      "IpcMode": "host",
      "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
      "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
      "Ulimits": [{"Name":"nofile", "Hard":10240, "Soft":10240}],
      "Privileged": false,
      "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
    }
}'''