[[apps]]
title = 'Desktop (xfce)'
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/xfce/assets/icon.png"

[apps.runner]
type = 'docker'
name = 'WolfXFCE'
image = 'ghcr.io/games-on-whales/xfce:edge'
env = ['GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*']
devices = []
mounts = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": true,
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  },
  "User": "0:0"
}
\
"""