[[apps]]
title = 'Bottles'
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/bottles/assets/icon.png"

[apps.runner]
type = 'docker'
name = 'WolfBottles'
image = 'ghcr.io/games-on-whales/bottles:edge'
env = ['RUN_SWAY=true', 'GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*']
devices = []
mounts = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": false,
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""