[[apps]]
title = "AudioRelay"
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/audiorelay/assets/icon.png"

[apps.runner]
type = "docker"
name = "WolfAudioRelay"
image = "ghcr.io/games-on-whales/audiorelay:edge"
mounts = []
env = [
    "RUN_SWAY=true",
    "GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*",
    'AUDIORELAY_ID=default', #set this an unique id for every profile, audiorelay will create virtual device according to this id

]
devices = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "NetworkMode": "host",
    "IpcMode": "host",
    "CapAdd": ["NET_RAW", "MKNOD", "NET_ADMIN"],
    "Privileged": false,
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""
