name: Automated builds

on:
  push:
    branches:
      - master
    paths:
      - "images/**"
      - ".github/workflows/*"
      - "apps/**"
      
#  schedule:
#    - cron: "0 0 * * *" # nightly

jobs:
  base:
    uses: ./.github/workflows/docker-build-and-publish.yml
    with:
      image_name: "base"
      platforms: "linux/amd64,linux/arm64"
    secrets: inherit

  base-app:
    needs: [ base ]
    uses: ./.github/workflows/docker-build-and-publish.yml
    with:
      image_name: "base-app"
      base_image: "${{ needs.base.outputs.image_tag }}"
      platforms: "linux/amd64,linux/arm64"
    secrets: inherit

  base-emu:
    needs: [ base, base-app ]
    uses: ./.github/workflows/docker-build-and-publish.yml
    with:
      image_name: "base-emu"
      base_image: "${{ needs.base.outputs.image_tag }}"
      base_app_image: "${{ needs.base-app.outputs.image_tag }}"
      platforms: "linux/amd64,linux/arm64"
    secrets: inherit

  emus:
    needs: [ base, base-app, base-emu ]
    strategy:
      matrix:
        image:
          - { name: pegasus,                    platforms: "linux/amd64" }
          - { name: es-de,                      platforms: "linux/amd64" }
      fail-fast: false
    uses: ./.github/workflows/docker-build-and-publish.yml
    with:
      image_name: "${{ matrix.image.name }}"
      base_image: "${{ needs.base.outputs.image_tag }}"
      base_app_image: "${{ needs.base-emu.outputs.image_tag }}"
      platforms: "${{ matrix.image.platforms }}"
    secrets: inherit

  apps:
    needs: [ base, base-app ]
    strategy:
      matrix:
        image:
          - { name: xorg,                       platforms: "linux/amd64" }
          - { name: pulseaudio,                 platforms: "linux/amd64,linux/arm64" }
          # udevd was an experiment it's definitely not needed anymore
          # - { name: udevd,                      platforms: "linux/amd64" }
          - { name: sunshine,                   platforms: "linux/amd64" }
          - { name: retroarch,                  platforms: "linux/amd64" }
          - { name: firefox,                    platforms: "linux/amd64,linux/arm64" }
          - { name: steam,                      platforms: "linux/amd64" }
          - { name: lutris,                     platforms: "linux/amd64" }
          - { name: heroic-games-launcher,      platforms: "linux/amd64" }
          - { name: prismlauncher,              platforms: "linux/amd64" }
          - { name: kodi,                       platforms: "linux/amd64" }
          - { name: xfce,                       platforms: "linux/amd64" }
      fail-fast: false
    uses: ./.github/workflows/docker-build-and-publish.yml
    with:
      image_name: "${{ matrix.image.name }}"
      base_image: "${{ needs.base.outputs.image_tag }}"
      base_app_image: "${{ needs.base-app.outputs.image_tag }}"
      platforms: "${{ matrix.image.platforms }}"
    secrets: inherit

